### ISSUE TITLE
Absorb dot-jaeger

### ISSUE THREAD

**Issue by drahnr** [paritytech/polkadot-introspector#25]
https://github.com/paritytech/dot-jaeger

was an initial tool to scrape jaeger spans and transform them into stages of a parachain candidate block. It never turned out to be as useful as anticipated, but the code for extracting the jaeger span metrics should be good enough.

Integrating that should also pave the way for using jaeger span based asserts in zombienet.

CC @dvdplm @pepoviola @sandreim 

Once this issue is closed, `dot-jaeger` should be archived.

**Comment by AndreiEres** [comment]
@vstakhov Do we still want to do this? Any ideas?
