### ISSUE TITLE
Set up proper versioning on docker tags

### ISSUE THREAD

**Issue by PierreBesson** [paritytech/polkadot-introspector#263]
Currently, this application docker image tags are unversioned (see https://hub.docker.com/r/paritytech/polkadot-introspector/tags) which makes it hard to manage rollout of new versions to staging/production environments.

**Comment by AndreiEres** [comment]
Fixed:
https://hub.docker.com/layers/paritytech/polkadot-introspector/v0.2.0/images/sha256-d9c5bd50f48e5c701f7064d78252d222b02ac3d083e50ca0eaa0b3eab381e33f?context=explore
