### ISSUE TITLE
Extract tools and core code into separate crates

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-introspector#275]
In the near future we must consider extracting the tools from the core code into crates and build them as separate binaries rather than subcommands of a swiss army knife.

**Comment by sandreim** [comment]
@vstakhov @AndreiEres please share thoughts on this

**Comment by vstakhov** [comment]
I have done some part of the refactoring in https://github.com/paritytech/polkadot-introspector/pull/268
So we have a workspace now and it won't be too hard to split the tool into several subprojects and hide some of them (e.g. kvdb) under features flags.
