### ISSUE TITLE
Improve accuracy of tracer block time metrics

### ISSUE THREAD

**Issue by sandreim** [paritytech/polkadot-introspector#368]
While analyzing the data collected via https://grafana.parity-mgmt.parity.io/goto/Vz-melU4R?orgId=1 it seems that we might have inaccurate metrics when rpc connection goes south as well due to scraping intervals, especially for histograms. 

We should explore some ways of improving on that.

**Comment by sandreim** [comment]
Maybe it is worth to have separate metrics for para block times in seconds also. This would make it more accurate as now we do multiply those by the relay block time.

**Comment by AndreiEres** [comment]
We added para block times in seconds recently. @sandreim What else do you think we could have done?

**Comment by sandreim** [comment]
I'd compare the numbers we get for kusama statemine block times (via collator metrics) with numbers we get from introspector for statemine.

Query for statemine metrics: `1/min(rate(substrate_block_height{chain="statemine"}[5m]) > 0) by (chain)`

If these are in sync we can close the issue otherwise I'd say we must dive deeper

**Comment by AndreiEres** [comment]
<img width="1462" alt="image" src="https://github.com/paritytech/polkadot-introspector/assets/27277055/f4be6e10-3de6-491c-8c85-7c0ca348767b">
https://grafana.parity-mgmt.parity.io/goto/6CT_D3uVg?orgId=1

On average, we have ~0.5s difference between metrics. If we consider collator's metrics as realistic, we should keep improving the accuracy.
