### ISSUE TITLE
"FATAL: cannot start kvdb tool: Invalid configuration: Not an indexed column."

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot-introspector#551]
I tried multiple node types and multiple database (paritydb/rocksdb) but I always get this error
```
FATAL: cannot start kvdb tool: Invalid configuration: Not an indexed column.
```

**Comment by AndreiEres** [comment]
@crystalin Sorry for a long response
Could you check if the issue is still present in the last version of polkadot-kvdb. If so, could you provide more details about how to reproduce the bug?

**Comment by AndreiEres** [comment]
Due to a lack of recent activity, I will close this issue for now. If the problem persists or you have new information to help reproduce the bug, please reopen this issue or create a new one.
